### PR TITLE
Disable bitcode on OS X

### PR DESCRIPTION
**Pull request by tonyarnold**

### CODE REVIEW

**Comment by NachoSoto** [comment]
This is not enabled in any other `xcconfig` file so I'm not sure it makes sense to explicitly disable it here.

**Comment by neilpa** [comment]
It seems to default to on, even for Mac projects so we should disable it here.

**Comment by NachoSoto** [comment]
It defaults to on? 😓
Wow, okay then!

**Comment by ikesyo** [comment]
Mac target defaults to off at least in Xcode 7.1.

**Pull request merged**
