### PR TITLE
Ignore Carthage/Build

### PR DESCRIPTION
**Pull request by sagmor**
When using this project as a dependency of a framework being built with [Carthage](https://github.com/Carthage/Carthage) in mind you always en up with `untracked content` changes that could be cleaned up just by ignoring `Carthage/Build`

### CODE REVIEW

**Comment by phatblat** [comment]
:+1:, but this only addresses the issue with this one dependency. It would be nice if Carthage could prime the `.git/info/exclude` with this when dependencies are checked out as submodules.

**Comment by sagmor** [comment]
At first I thought of adding it to my global `.gitignore` and forget about it.

The problem with both approaches is that ignoring `Carthage/Build` makes total sense for a framework/dependency but might not be wanted on an application in which you might prefer to keep the built dependencies versioned.

**Comment by tomassliz** [comment]
@sagmor I agree with your opinion. So one way is to try make pull request to 3rd party frameworks and hope, that they will be accepted. Second way is just ignore it and be careful while I make commit.

**Comment by sagmor** [comment]
At first I ignored dirty tracking on submodules like:
```
[submodule "Carthage/Checkouts/xcconfigs"]
    path = Carthage/Checkouts/xcconfigs
    url = git://github.com/jspahrsummers/xcconfigs.git
    ignore = dirty
```

It's a nice option to begin with, but felt `dirty` (pun intended :facepunch: jeje).
But then I began to modify some of the frameworks I was working with, so that flag was a problem. Now, given the distributed nature of Carthage, it's as simple as pointing to a fork and ignoring yourself.
Finally pushing a pull request and return to upstream when merged :sparkles: 

That's how this PR was born on the first place :sunrise:

**Comment by jspahrsummers** [comment]
Sorry about the delay in reviewing this—I was on vacation. This looks good, thanks for the PR! :sparkles:

**Comment by sagmor** [comment]
Awesome :smile:

**Pull request merged**
