### PR TITLE
Disable framework code signing for successful device builds with Xcode 8

### PR DESCRIPTION
**Pull request by ikesyo**
See https://github.com/Carthage/Carthage/issues/1378 for the details.

### CODE REVIEW

**Comment by mdiep** [comment]
Looks good to me. 👍

**Comment by NachoSoto** [comment]
Can you add a comment explaining that they do need to be signed, but not at compile time?

**Comment by ikesyo** [comment]
Thanks for the review! Updated the comments thanks to the @mdiep's one in https://github.com/Carthage/Carthage/issues/1378#issuecomment-229646114. 🙏

**Comment by NachoSoto** [comment]
:+1:

**Pull request merged**
